# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: 党洁的博客

description: 党洁的博客 关注移动互联网开发 开源爱好者
author:
  name: 党洁
  email: 418696850@qq.com
  github: jiedang
  
rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH: dangjie.me
